version: '3.7'

#We define the services here.
services:
  #Backend service
  backend:
    build:
      #run the Dockerfile of the backend
      context: backend
      dockerfile: Dockerfile
    #le container créé s'apellera backend
    container_name: backend
    networks:
      - app-network

  #Database service
  database:
    build:
      # run the dockerfile of the database
      context: database
      dockerfile: Dockerfile
    container_name: database
    env_file:
      - .env
    #the database runs on port 5432
    ports:
      - "5432:5432"
    networks:
      - app-network

  #Proxy service
  httpd:
    build:
      #run the Dockerfile of the proxy
      context: frontend
      dockerfile: Dockerfile
    container_name: frontend
    #The proxy runs on port 81
    ports:
      - "81:80"
    networks:
      - app-network

#We define a network to allow the containers to exchange data
networks:
  app-network: