- name: Run Backend
  #Creation of a Docker container with the image of the backend.
  docker_container:
    name: backend
    image: abourliatoux7/tp-devops-backend:latest
    pull: true
    recreate: true
    networks:
      - name: app-network


