name: CI devops 2023
on:
  #we want to launch this job in master
  push:
    branches:
      - master
  pull_request:

#We defined 2 jobs: test-backend and build-and-push-docker-image
jobs:
  #Job to test the backend
  test-backend: 
    runs-on: ubuntu-22.04
    steps:
     #checkout your github code using actions/checkout@v2.5.0
      - name: Checkout code
        uses: actions/checkout@v2.5.0

      #We set up the JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'adopt'

      #We'll use SonarCloud and Maven for more efficiency
      - name: Cache SonarCloud packages
        uses: actions/cache@v3
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar
      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      #We build and analyze the code in the backend directory using Maven and SonarCloud
      - name: Build and analyze
        working-directory: backend
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=devops-aurelien


  build-and-push-docker-image:
    #this job is in completion of the test-backend job
    needs: test-backend
    runs-on: ubuntu-22.04
    steps:
      #Checks out the code from the repository
      - name: Checkout code
        uses: actions/checkout@v2.5.0

      #Logs in to DockerHub with the connection parameters
      - name: Login to DockerHub
        run: docker login -u ${{ secrets.USER_DOCKER }} -p ${{ secrets.TOKEN_DOCKER }}

      #Builds Docker images for the backend, database, and frontend from their respective directories.
      #The images are tagged with the latest version.
      - name: Build image and push backend
        uses: docker/build-push-action@v3
        with:
          context: ./backend
          tags: ${{secrets.USER_DOCKER}}/tp-devops-backend:latest
          push: ${{ github.ref == 'refs/heads/master' }}

      - name: Build image and push database
        uses: docker/build-push-action@v3
        with:
          context: ./database
          tags: ${{secrets.USER_DOCKER}}/tp-devops-database:latest
          push: ${{ github.ref == 'refs/heads/master' }}

      - name: Build image and push frontend
        uses: docker/build-push-action@v3
        with:
          context: ./frontend
          tags: ${{secrets.USER_DOCKER}}/tp-devops-frontend:latest
          push: ${{ github.ref == 'refs/heads/master' }}


