name: CI devops 2023
on:
  #to begin you want to launch this job in main and develop
  push:
    branches:
      - ci-cd
  pull_request:

jobs:
  test-backend: 
    runs-on: ubuntu-22.04
    steps:
     #checkout your github code using actions/checkout@v2.5.0
      - name: Checkout code
        uses: actions/checkout@v2.5.0

      - name: Login to DockerHub
        run: docker login -u ${{ secrets.USER_DOCKER }} -p ${{ secrets.TOKEN_DOCKER }}

      - name: Build image and push backend
        uses: docker/build-push-action@v3
        with:
          # relative path to the place where source code with Dockerfile is located
          context: ./backend
          # Note: tags has to be all lower-case
          tags: ${{secrets.USER_DOCKER}}/tp-devops-backend:latest
          push: ${{ github.ref == 'refs/heads/ci-cd' }}

      - name: Build image and push database
        uses: docker/build-push-action@v3
        with:
          # relative path to the place where source code with Dockerfile is located
          context: ./database
          # Note: tags has to be all lower-case
          tags: ${{secrets.USER_DOCKER}}/tp-devops-database:latest
          push: ${{ github.ref == 'refs/heads/ci-cd' }}

      - name: Build image and push frontend
        uses: docker/build-push-action@v3
        with:
          # relative path to the place where source code with Dockerfile is located
          context: ./frontend
          # Note: tags has to be all lower-case
          tags: ${{secrets.USER_DOCKER}}/tp-devops-frontend:latest
          push: ${{ github.ref == 'refs/heads/ci-cd' }}

     #do the same with another action (actions/setup-java@v3) that enable to setup jdk 17
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'adopt'

     #finally build your app with the latest command
      - name: Build and test with Maven
        working-directory: backend
        run: mvn clean verify
